"""
Argument model — the universal data contract across all subsystems.

Every subsystem's output eventually becomes one or more Argument objects.
The 8-field schema derives from Toulmin's argument model (L-19):
  claim, data (→ evidence), warrant, plus metadata fields.

Design notes:
  - cause_categories is required and non-empty (decision #1 from architecture).
    The Kostenko KB needs backfilling before it loads through this schema.
  - confidence is a float 0.0–1.0 (matches existing KB data). The architecture
    doc mentions high/medium/low — that's a display concern, not schema.
  - source identifies which expert or agent produced the argument.
  - Arguments from human experts (v1 input) and LLM agents (v4 output) use
    the same schema — everything downstream is source-agnostic.
"""

from __future__ import annotations

from pydantic import BaseModel, Field, field_validator


class Argument(BaseModel):
    """
    A single structured argument from an expert report or agent analysis.

    Examples:
        U-A1: "Initial ignition occurred at sections 142-145" (Usembekov)
        K-A4: "AFC conveyor sparking was the most probable ignition source" (Kolikov)
        agent_1_001: (generated by Technical Causes Analyst in v4)
    """

    id: str = Field(
        ...,
        min_length=1,
        description=(
            "Unique argument ID. Convention: "
            "'{source}-A{n}' for expert args (e.g. 'U-A1', 'K-A4', 'D-A5'), "
            "'agent_{n}_{seq}' for agent-generated args"
        ),
    )
    source: str = Field(
        ...,
        min_length=1,
        description=(
            "Who produced this argument. "
            "Expert IDs ('U', 'K', 'D') for Kostenko, "
            "agent IDs ('agent_1'..'agent_4') for system output"
        ),
    )
    topic: str = Field(
        ...,
        min_length=1,
        description=(
            "The investigation question this argument addresses. "
            "Used by v5 for topic-based conflict detection — arguments on the "
            "same topic are candidate attack/support pairs. "
            "Examples: 'Ignition source', 'Spontaneous combustion', 'Explosion type'"
        ),
    )
    claim: str = Field(
        ...,
        min_length=1,
        description="The conclusion being asserted",
    )
    evidence: str = Field(
        ...,
        min_length=1,
        description="The data/observations supporting the claim (Toulmin's 'data')",
    )
    warrant: str = Field(
        ...,
        min_length=1,
        description="The reasoning connecting evidence to claim (Toulmin's 'warrant')",
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence in the claim, 0.0–1.0",
    )
    cause_categories: list[str] = Field(
        ...,
        min_length=1,
        description=(
            "One or more cause category IDs from the taxonomy (e.g. 'TC-01', 'OC-04'). "
            "Required and non-empty — this is what v2 classification and v3 matching use."
        ),
    )

    @field_validator("cause_categories")
    @classmethod
    def _validate_cause_ids(cls, v: list[str]) -> list[str]:
        import re
        pattern = re.compile(r"^(TC|OC)-\d{2}$")
        bad = [cid for cid in v if not pattern.match(cid)]
        if bad:
            raise ValueError(
                f"Invalid cause category IDs: {bad}. Expected format: TC-XX or OC-XX"
            )
        return v