"""
V6Report — output of the final report-generation stage.

Two-tier structure:
  V6ReportContent  — sections of the report as markdown strings. This is
                     what the LLM directly produces (Pydantic-validated).
  V6Report         — the full report including the LLM content plus
                     deterministic data (run_id, case metadata, graph path).

The renderer (`src/v6_report/renderer.py`) turns a V6Report into a single
markdown or HTML document with proper section headers, graph embed, and
traceability index.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class V6ReportContent(BaseModel):
    """
    The seven narrative sections of the investigation report.

    Each section is a markdown string ready for direct rendering. The LLM
    generates this in a single call, given the full pipeline context as
    input. Sections may include argument-ID citations like `[U-A1]` or
    `[agent_3_001]` — the renderer leaves these as-is for traceability.

    Section 6 (Argumentation graph) is not generated by the LLM — it is a
    deterministic PNG render of the AF, embedded into the markdown by the
    renderer separately.
    """

    incident_summary: str = Field(
        ...,
        description=(
            "Section 1 — Incident summary. Case name, date, location, "
            "casualties, brief overview of the event. Drawn from v1 metadata."
        ),
    )
    classification_and_precedents: str = Field(
        ...,
        description=(
            "Section 2 — Accident classification (primary + secondary types) "
            "and ranked precedent matches. Drawn from v2 + v3 outputs."
        ),
    )
    accepted_conclusions: str = Field(
        ...,
        description=(
            "Section 3 — What the system concludes with confidence. "
            "Members of the grounded extension, organized by topic, with "
            "argument-ID citations and a narrative explaining the consensus."
        ),
    )
    rejected_hypotheses: str = Field(
        ...,
        description=(
            "Section 4 — Hypotheses the framework defeated. Each rejected "
            "argument is named, the attacking argument(s) cited, and the "
            "reasoning for rejection explained."
        ),
    )
    unresolved_questions: str = Field(
        ...,
        description=(
            "Section 5 — Genuinely contested arguments (in some preferred "
            "extension but not all). Includes the open questions flagged by "
            "the original investigators."
        ),
    )
    regulatory_violations: str = Field(
        ...,
        description=(
            "Section 7 — Regulatory compliance findings from Agent 4. "
            "Each finding cites a specific regulation and the evidence."
        ),
    )


class V6Report(BaseModel):
    """The full v6 output: LLM narrative + deterministic data."""

    content: V6ReportContent
    case_name: str
    case_date: str
    run_id: str
    graph_path: str = Field(
        ...,
        description="Path to the rendered AF graph PNG (relative to run_dir).",
    )
    counts: dict[str, int] = Field(
        default_factory=dict,
        description="Summary counts: arguments, attacks, supports, accepted, etc.",
    )
